spring:
  datasource:
    url: jdbc:h2:mem:testdb    driver-class-name: org.h2.Driver
    data:    - classpath:schema.sql
    - classpath:data.sql
  h2:    console:      enabled: true

# mybatis config
mybatis:  type-aliases-package: com.play.waco.entity

logging:  level:    com.play.waco.mapper: trace
