INSERT INTO GYM (NAME, ADDR1, ADDR2, ZIPCODE, TELNO, EMAIL, MOBILENO, MASTER, STAFF, INFO)
VALUES ('JHGYM', '인천 계양구 A', '황어로 A', '111-111', '032-111-1111', 'JHGYM@AAA.COM', '010-1111-1111', 1, 1, 'A TYPE');

INSERT INTO GYM (NAME, ADDR1, ADDR2, ZIPCODE, TELNO, EMAIL, MOBILENO, MASTER, STAFF, INFO)
VALUES ('BBGYM', '인천 계양구 B', '황어로 B', '222-222', '032-222-2222', 'BBGYM@BBB.COM', '010-2222-2222', 2, 2, 'B TYPE');

INSERT INTO GYM (NAME, ADDR1, ADDR2, ZIPCODE, TELNO, EMAIL, MOBILENO, MASTER, STAFF, INFO)
VALUES ('CCGYM', '인천 계양구 C', '황어로 C', '333-333', '032-333-3333', 'CCGYM@CCC.COM', '010-3333-3333', 3, 3, 'C TYPE');

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (1, '손영수', 'M', '111111', 'ADFASJFD;AF', 74, 177, '010-111-1111', 0, 0, 0); 

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (1, 'B', 'M', '222222', 'ADFASJFD;AF', 74, 177, '010-222-2222', 0, 0, 0);

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (1, 'C', 'M', '333333', 'ADFASJFD;AF', 74, 177, '010-333-3333', 0, 0, 0);

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (2, 'D', 'M', '444444', 'ADFASJFD;AF', 74, 177, '010-444-4444', 0, 0, 0);

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (2, 'E', 'M', '555555', 'ADFASJFD;AF', 74, 177, '010-555-5555', 0, 0, 0);

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (2, 'F', 'M', '666666', 'ADFASJFD;AF', 74, 177, '010-666-6666', 0, 0, 0);

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (3, 'G', 'M', '777777', 'ADFASJFD;AF', 74, 177, '010-777-7777', 0, 0, 0);

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (3, 'H', 'M', '888888', 'ADFASJFD;AF', 74, 177, '010-888-8888', 0, 0, 0);

INSERT INTO PLAYER (GYM, NAME, SEX, SSN_FRONT, SSN_ENCRIPT, WEIGHT, HEIGHT, TELNO, WIN, LOSE, TIE)
VALUES (3, 'I', 'M', '999999', 'ADFASJFD;AF', 74, 177, '010-999-9999', 0, 0, 0);

INSERT INTO MATCH (NAME, TIME, STARTDATE, ENDDATE, ADDR1, ADDR2, SPONSOR)
VALUES ('인천 계양구배', 1, '2019-02-28', '2019-02-28', '인천 계양구', '황어 체육관', '계양구청');

INSERT INTO MATCH_EVENT (NAME, INFO, REGDATE)
VALUES ('point fighting', '포인트 제', NOW());

INSERT INTO MATCH_EVENT (NAME, INFO, REGDATE)
VALUES ('kick light', '점수 제', NOW());

INSERT INTO MATCH_EVENT (NAME, INFO, REGDATE)
VALUES ('meet', '자세 점수', NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 1, 9, NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 2, 9, NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 3, 9, NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 4, 9, NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 5, 9, NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 6, 9, NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 7, 9, NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 8, 9, NOW());

INSERT INTO MATCH_REGISTER (MATCHID, EVENTID, PLAYERID, WEIGHT_DIVISION, REGDATE)
VALUES (1, 1, 9, 9, NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (0, 47, 'Y', '라이트플라이급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (48, 50, 'Y', '플라이급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (51, 53, 'Y', '밴텀급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (54, 56, 'Y', '페더급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (57, 59, 'Y', '라이트급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (60, 63.4, 'Y', '라이트웰터급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (63.5, 66, 'Y', '웰터급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (67, 70, 'Y', '라이트미들급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (71, 74, 'Y', '미들급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (75, 80, 'Y', '라이트헤비급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (81, 90, 'Y', '헤비급', NOW());

INSERT INTO WEIGHT_DIVISION (START, END, AMATEUR_YN, INFO, REGDATE)
VALUES (91, 200, 'Y', '슈퍼헤비급', NOW());