DROP TABLE IF EXISTS GYM;

CREATE TABLE GYM (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR,
	ADDR1 VARCHAR,
	ADDR2 VARCHAR,
	ZIPCODE VARCHAR,
	TELNO VARCHAR,
	MOBILENO VARCHAR,
	EMAIL VARCHAR,
	MASTER INT,
	STAFF INT,
	INFO VARCHAR
);