DROP TABLE IF EXISTS GYM;

CREATE TABLE GYM (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR,
	ADDR1 VARCHAR,
	ADDR2 VARCHAR,
	ZIPCODE VARCHAR,
	TELNO VARCHAR,
	MOBILENO VARCHAR,
	EMAIL VARCHAR,
	MASTER INT,
	STAFF INT,
	INFO VARCHAR
);

DROP TABLE IF EXISTS Player;

CREATE TABLE Player (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	GYM INT,
	NAME VARCHAR,
	SEX INT,
	SSN_FRONT VARCHAR,
	SSN_ENCRIPT VARCHAR,
	TELNO VARCHAR,
	WIN INT,
	LOSE INT,
	TIE INT
);

DROP TABLE IF EXISTS MATCH;

CREATE TABLE MATCH (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR,
	TIME INT,
	STARTDATE VARCHAR,
	ENDDATE VARCHAR,
	ADDR1 VARCHAR,
	ADDR2 VARCHAR,
	SPONSOR VARCHAR
);
