DROP TABLE IF EXISTS GYM;

CREATE TABLE GYM (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR,
	ADDR1 VARCHAR,
	ADDR2 VARCHAR,
	ZIPCODE VARCHAR,
	TELNO VARCHAR,
	MOBILENO VARCHAR,
	EMAIL VARCHAR,
	MASTER INT,
	STAFF INT,
	INFO VARCHAR
);

DROP TABLE IF EXISTS PLAYER;

CREATE TABLE PLAYER (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	GYM INT,
	NAME VARCHAR,
	SEX VARCHAR,
	SSN_FRONT VARCHAR,
	SSN_ENCRIPT VARCHAR,
	WEIGHT INT,
	HEIGHT INT,
	TELNO VARCHAR,
	WIN INT,
	LOSE INT,
	TIE INT
);

DROP TABLE IF EXISTS MATCH;

CREATE TABLE MATCH (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR,
	TIME INT,
	STARTDATE VARCHAR,
	ENDDATE VARCHAR,
	ADDR1 VARCHAR,
	ADDR2 VARCHAR,
	SPONSOR VARCHAR
);

DROP TABLE IF EXISTS MATCH_EVENT;

CREATE TABLE MATCH_EVENT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR,
	INFO VARCHAR,
	REGDATE DATETIME DEFAULT NOW()
);

DROP TABLE IF EXISTS MATCH_REGISTER;

CREATE TABLE MATCH_REGISTER (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	MATCHID INT,
	EVENTID INT,
	PLAYERID INT,
	WEIGHT_DIVISION INT, 
	REGDATE DATETIME DEFAULT NOW()
);

DROP TABLE IF EXISTS WEIGHT_DIVISION;

CREATE TABLE WEIGHT_DIVISION (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	START DECIMAL(4,1),
	END DECIMAL(4,1),
	AMATEUR_YN CHAR DEFAULT 'Y',
	INFO VARCHAR,
	REGDATE DATETIME DEFAULT NOW()
);